### ISSUE TITLE
Plugin breaks links to comments

### ISSUE THREAD

**Issue by doleks** [underblob/WhiteSpace-Bitbucket#3]
BigBucket behaves strangely when ?w=1 parameter is added to the link in the form https://bitbucket.org/some_repository/pull-request/444/some_pull_request#comment-444 . 
Instead of going to that comment it just redirects the page to 
https://bitbucket.org/some_repository/pull-request/444/some_pull_request

The right way for plugin will be not to add a parameter if the link contains a selector.

**Comment by doleks** [comment]
Added pull request https://github.com/underblob/WhiteSpace-Bitbucket/pull/4

**Comment by underblob** [comment]
Thanks for brining this to my attention. Fixed in this commit: https://github.com/underblob/WhiteSpace-Bitbucket/commit/27b8d05b1fe45799f4f6d32594448885a6748e6c
