### ISSUE TITLE
When viewing branches, the diff doesn't ignore whitespace

### ISSUE THREAD

**Issue by stevebeck89** [underblob/WhiteSpace-Bitbucket#8]
If you are viewing a branch, for example:

https://bitbucket.org/owner/app/branch/some_branch_name, ideally the "w=1" parameter is added.

**Comment by underblob** [comment]
@stevebeck89, the org I'm with is no longer on Bitbucket so I'm not maintaining this Chrome extension anymore. Let me know if would be interested in taking over the project.
